### ISSUE TITLE
Packaging pdfmm on conda-forge

### ISSUE THREAD

**Issue by xmnlab** [pdfmm/pdfmm#35]
Hi everyone! 

Currently I am packing that to conda-forge. If anyone wants to take a look into that before it is merged: https://github.com/conda-forge/staged-recipes/pull/20334/files

let me know if it needs any specific pinning there. I didn't find here any list of the dependencies with the versions that should work with pdfmm.

hope to have that merged really soon :)

**Comment by ceztko** [comment]
I don't have time to follow external packaging solutions but thank you. Also, please note pdfmm is merging back to the parent project PoDoFo within this year[1][2]. Please subscribe to [PoDoFo](https://sourceforge.net/projects/podofo/lists/podofo-users) mailing lists for news.

[1] https://www.mail-archive.com/podofo-users@lists.sourceforge.net/msg04718.html
[2] https://www.mail-archive.com/podofo-users@lists.sourceforge.net/msg04850.html

**Comment by xmnlab** [comment]
thanks @ceztko for pointing me to that. I will suscribe me to podofo mailing list. thanks!
