### ISSUE TITLE
How to replace PoDoFo::PdfSignatureField with mm::PdfSignature

### ISSUE THREAD

**Issue by ferencIOS** [pdfmm/pdfmm#41]
Basically I am trying to rewrite the [podofosign tool](https://github.com/podofo/podofo/blob/master/tools/podofosign/podofosign.cpp)

Currently I don't know how to write these portions of code

**CASE 1** (PdfAnnotation already exists which needs an update)

```
            pTemporaryAnnot = new PdfAnnotation( pExistingSigField, pPage );
            if( !pTemporaryAnnot )
                PODOFO_RAISE_ERROR_INFO( ePdfError_OutOfMemory, "Cannot allocate annotation object for existing signature field" );

            pSignField = new PdfSignatureField( pTemporaryAnnot );
            if( !pSignField )
                PODOFO_RAISE_ERROR_INFO( ePdfError_OutOfMemory, "Cannot allocate existing signature field object" );
```

**CASE 2** (PdfAnnotation which must be created from scratch)

```
            PdfAnnotation* pAnnot = pPage->CreateAnnotation( ePdfAnnotation_Widget, annot_rect );
            if( !pAnnot )
                PODOFO_RAISE_ERROR_INFO( ePdfError_OutOfMemory, "Cannot allocate annotation object" );

            if( annot_position && annot_print )
                pAnnot->SetFlags( ePdfAnnotationFlags_Print );
            else if( !annot_position && ( !field_name || !field_use_existing ) )
                pAnnot->SetFlags( ePdfAnnotationFlags_Invisible | ePdfAnnotationFlags_Hidden );

            pSignField = new PdfSignatureField( pAnnot, pAcroForm, &document );
```

**CASE 3**

```
                PdfRect annotSize( 0.0, 0.0, annot_rect.GetWidth(), annot_rect.GetHeight() );
                PdfXObject sigXObject( annotSize, &document );
```

What i am trying to write

**ATTEMPT 1**
```   
        std::unique_ptr<PdfAnnotation> tempAnnot = std::make_unique<PdfAnnotation>(pTemporaryAnnot);
        
        if ( !PdfAnnotation::TryCreateFromObject<PdfAnnotation>(*pExistingSigField, tempAnnot) )
        {
            MM_RAISE_ERROR_INFO( PdfErrorCode::OutOfMemory, "Cannot allocate annotation object for existing signature field" );
        }
        
        if( !pExistingSigField->GetDictionary().HasKey( "V" ) )
        {
            MM_RAISE_ERROR_INFO( PdfErrorCode::InvalidKey, "Cannot find 'V' key" );
        }
        
        std::unique_ptr<PdfField> signField = std::make_unique<PdfField>(pSignField);
        
        PdfObject *obj = pExistingSigField->GetDictionary().FindKey( "V" );
        
        if ( !PdfSignature::TryCreateFromObject(*obj, signField) )
        {
            // TODO: raise error
        }

        if( !pSignField )
        {
            MM_RAISE_ERROR_INFO( PdfErrorCode::OutOfMemory, "Cannot allocate existing signature field object" );
        }
```

**ATTEMPT 2**
it seems paradoxical but I didn't understand how to create a PdfSignature from scratch (starting from a ``PdfRect annot_rect``)

**ATTEMPT 3**
```

        PdfObject *rect_obj = pExistingSigField->GetDictionary().GetKey("Rect");
        
        PdfXObjectForm *sigXObject;
        std::unique_ptr<PdfXObjectForm> sigObject = std::make_unique<PdfXObjectForm>(sigXObject);

        if ( !PdfXObjectForm::TryCreateFromObject(*rect_obj, sigObject) )
        {
            // TODO: raise error
        }
```

I noticed that the _utility constructors_ are all private, I guess for a precise choice, it seems that the idea is to use `TryCreateFromObject`.

Also I realized that a concrete class of the `PdfSigner` is missing.

Thanks for your help!

**Comment by ceztko** [comment]
A untested port of podofosign can be found [here](https://github.com/pdfmm/pdfmm/blob/PoDoFoTools/tools/podofosign/podofosign.cpp).

About your requests:

CASE 1:
- Iterate page annoations with `PdfPage::GetAnnotations`, select widget annotations and cast them to `PdfAnnotationWidget`, get the field with `PdfAnnotationWidget::GetField()`, select the signature fields only and cast them to `PdfSignature`. A direct API to iterate fields in page may come later;

CASE2:
`PdfPage::CreateField<PdfSignature>(name, rect)`

CASE3:
Not sure what you need here but you can create an `PdfXObjectForm` to use as a signature appearance with `PdfDocument::CreateXObjectForm()`. You can parse an existing object, possibly extracted from the `/AP` appearance dictionary of the signature, using `PdfXObject::TryCreateFromObject()` with a `PdfObject` as an input.
